# -*- coding: utf-8 -*-
"""
Created on Mon Dec 20 01:26:19 2021

@author: Gabriel
"""

txt = "TCGTCAGCTATCGTCAGCACGTCAGCGTCGTCAGCTCTCCGTCAGCCTGATCGTCAGCCGTCAGCTCCAAGAGGCCGTCAGCGACGTCAGCCGTCAGCCCGCGTCAGCTTACGTCAGCCGTCAGCAGCGTCAGCCGTCAGCCTCGTCAGCTCGTCAGCCCAATCATCCCGTCAGCAACCGTCAGCTGCGTCAGCTCGTCAGCCGTCAGCCGTCAGCCCAAGGCGTCAGCACGCGTCAGCCGTCAGCCGTCAGCCGTCAGCCCGTCAGCCCCAGTCGTCAGCGGGCGTCAGCCGTCAGCCGTCAGCCGTCAGCACCAAGGAGTGCGTCAGCAAGCGATGCCGTCAGCCGTCAGCGGTCGTCAGCTTCGTCAGCCACGTCAGCCACTCACCGTCAGCTCGTCAGCTCGTCAGCTCTACCGTCAGCGATCGCGTCAGCGCGCCGTCAGCCCCTACCCGTCAGCCTCGTCAGCCGTCAGCATCCCAGCCGTCAGCGAGGGTGATAGCGTCAGCCAGCAGGTTCGTCAGCTGAAACGTCAGCATCCGTCAGCCCACGTCAGCGGGGGCGTCAGCCGTCAGCCGTCAGCCTCCATCCTTAGCGTCAGCCAGCGTCAGCCGCCCGCGTCAGCCTACCGTCAGCTCGAGACGTCAGCCTATACGTCAGCGCGTCAGCTCAACGTCAGCTCGTCAGCGGATGTTGACCGACGTCAGCCGTCAGCACCCGTCAGCGCCGCGTCAGCACGTCAGCTCACCGTCAGCGGCGTCAGCTCCGTCAGCACGTCAGCCGTCAGCGAGCGTCAGCCGTCAGCGCGGAGGCGTCAGCCTCACCTAATTCGTCAGCGGGCACCGTCAGCTCGTCAGCGTCGTCAGCCGTCAGCATCATCGTCAGCCGTCAGCCGTCAGCTCGTCAGCGCCCGTCAGCCCGTCAGCGTCCTCGCGTCAGC"
sub = "CGTCAGCCG"
fim = len(txt)
out = []

for i in range (fim):
    res = txt.find(sub, i, fim)
    if res == -1:
        break
    elif res == i:
        out.append(res+1)

print(out)