# -*- coding: utf-8 -*-
"""
Created on Fri Dec 17 23:18:57 2021

@author: Gabriel
"""


texto = "CACATCGGATGGATATTGGGCTTGTAAAGAATACTTAGGGACACAAGAACTCGTGAACAAGGATCGAAACTCTGTGAATGCTTCAGCCTGCTCTCAGTATAATCATAGCTGATTGGCACACTTCTCACTATCTATTCCCATGATCCCGCCGTCACACGACCTAAGTTGCACCGACCGTCGCTATTGGGGATAGAGCGCAACCGCCCAGAGCAAGCCCGAACTGAGGATAAAGCGATAATGACAAAAGCCGGCACCCAACGAGTTACCTTGCAAATTCACATTGCGAAGCGACGCTTTCACTGACTCCGAGGCAGTGGACAGCGAGGCGACCTCCAGTGAGCCGTACTTGTTGTCCTGGGCTCCCCACCACCCTTTGGCCGATTGAAGTGAGTTGATCGCCTGTTATATGGACTGTGGTCTATCTTATTCCTTCAAAGAAAAGCGTCATGAGACGAAAGATTCTGTTTCTGAACAGGAGCTGCCCATCGTTATCGTTCCGAAGAACACCAGTCTTAAAATCAGCCCTAATGTTATTACCCATATTCGGAACCGGATGCATCAAACTAATCTACCTAAGTGGGATACTTGCACGTTCGTATCGAGCCTCGACGTTTAACCCAGCACATGCAACTTTTTCTTAATTCGGTGTCCTGCTAGCGTGTAGCACTGTCCCGTTGGGACGCGTCAGGAGTACAAAGTTTTTTAGGCGCACCCATTATTCGTGTAACATATCCTAACAGGAGCCATTGGGCTCCTGACAGTACGGGATTGTATCGCATGCAATCTGGAATAGATAGAATCTCTATGG"
texto = texto[::-1]

"""
#Método 1
transTable = texto.maketrans("ATCG", "TAGC")
trans = texto.translate(transTable)
"""

#Método 2
dictio = { #translate() só funciona com dicionário se as chaves forem o valor do ascii
    ord("A") : "T", 
    ord("T") : "A",
    ord("C") : "G",
    ord("G") : "C"    
    }
    
trans = texto.translate(dictio)

print(trans)