# -*- coding: utf-8 -*-
"""
Created on Sat Dec 18 01:17:44 2021

@author: Gabriel
"""
protein_dictio = { #dicionario que traduz cada codon em um aminoacido
    "UUU" : "F",      "CUU" : "L",    "AUU" : "I",
    "GUU" : "V",      "UUC" : "F",    "CUC" : "L",
    "AUC" : "I",      "GUC" : "V",    "UUA" : "L",
    "CUA" : "L",      "AUA" : "I",    "GUA" : "V",
    "UUG" : "L",      "CUG" : "L",     "AUG" : "M", #Metionina, comeco de qqr proteina
    "GUG" : "V",      "UCU" : "S",   "CCU" : "P",    
    "ACU" : "T",      "GCU" : "A",
    "UCC" : "S",      "CCC" : "P",     "ACC" : "T",     "GCC" : "A",
    "UCA" : "S",      "CCA" : "P",     "ACA" : "T",     "GCA" : "A",
    "UCG" : "S",      "CCG" : "P",      "ACG" : "T",      "GCG" : "A",
    "UAU" : "Y",      "CAU" : "H",      "AAU" : "N",      "GAU" : "D",
    "UAC" : "Y",      "CAC" : "H",      "AAC" : "N",      "GAC" : "D",
    "UAA" : "Stop",   "CAA" : "Q",      "AAA" : "K",      "GAA" : "E",
    "UAG" : "Stop",   "CAG" : "Q",      "AAG" : "K",      "GAG" : "E",
    "UGU" : "C",      "CGU" : "R",      "AGU" : "S",      "GGU" : "G",
    "UGC" : "C",      "CGC" : "R",      "AGC" : "S",      "GGC" : "G",
    "UGA" : "Stop",   "CGA" : "R",      "AGA" : "R",      "GGA" : "G",
    "UGG" : "W",      "CGG" : "R",      "AGG" : "R",      "GGG" : "G"   
    }

txt = "AUGUGCACACAUAAGCUAGAGCAUCCGUCCCACAAACGAUCCGCAGUUCGGGUGAGAGGCCACCGCUCCCGAGUAAGUCUUGUCAGAGCUAUGAUCCAGCUUCAUUCUCAAGAUAAAGUUAAAAAGUACGGUAUUAAGGUUACAGCCGACAAUGUGCUGCCCCGUUCAGAGGCGUGCGUUUGCUUGUCCCCAUCGAAGGCCAUACCCCCUAGCUUUGGGAGAGUGGAGGUGCUGGAUAGUGUUUACUACAUCAGUUCUGAGGUUGACCGUGCUGUUUUUCCAACCAAACCGGCGCCGUCCAUGCGUUGGCCAACGAUCUGUGAGUCACGCAUAAGAGACCUUCUGUGGCCGUGUGCAAGGCGCGUCCGCCUUUUUCUUUGCAUACUGUGUAGGUCUGCUAGAACGACGAUCCUUAAGAGGCUGACCCUCCUUGCUCGGAGUACCCGGAAGUUCAACUCUCUCCGAUCAUGCCUGGGGAAUAUUAGUCCACCCCGAGAGACACACCGCUACGGCAUAUGGCAAUCCAAGAAAUGUGACGAUUAUAUGUUAUAUAAACCACGCUGCACUGUUAGACAUGCGUUAUGCUUAAGUGAUGUCCAACCCCGGCUAGAUGCCCGGCUUUCGGGUCCCUUUACUGUAGGCACCGGCCGAGAGAUUCCAUCAGUAUCUUGUAGAAAGGUGCAGGCUGACUUGUACUUAAGCGUAGACAGCGCGCUAGGGGCAUCCGUGCGUACUGGUCAACAGCAAUACAGACCUGUGUCGAGAUUAUACAAGGCUAGUAUUGACGCGAGUGACAUCUGGGAGCGCAUGGUUAGAGAUACUUACGAUGGUCUAGAGCCAAAUGUUAGUCGCCAGACGUUCGCCGUCCCCCACGACUGGCUAGAUCAGGAGAAUUGGAAAAUCCCUUGGACUAAUCCUCAUGAUUCAAUCCGAGCAGCGCGUGGUACUAUUCCAGCCCUAAGCGCCGAGAGGCAACCGUGGGCUGACUAUCUAAAGACAAAGGCAGCCCACUUAGAGACCCACUAUUGUCGAAUCGGUGGGAGAUCUGGAAAGUCUUGGUCCGUUACUGCCAGAGGAAGAGCACGAGGUCAAGUACAAAUUCCGAGCAGUCCUCGGUUUUGCAUCCUAAAUGGGAUCAUCAUAAACACCUCCCCUUUUUAUGCGGUAUGGCUGGCUCGAUCACCCCCCGCUCCUACAAGAUGCUUUCCGAAAUACCAGCCCUUGCCCAGUACUCAGGGGCUAAUAUUGACCAGCCUGUCUGAGGGGAAUACGGACUAUACUGCCGGUUGUUAUAUUAGCAUAUGUGGUCUACACCAAGCGCACAUGCCUAGGCGUGUUGCAUUACGGGUACUCAAUAAGCAUACAAUGGAAACCGUGCCACGAGUCGUGGUCUUGGAGAUGUGUGGUCUUGUGGAAAUCUGUUGUGAACUGCUACACUCAAAUUACCUAGGUUGCUUUCCCUUUCGUCAGUAUUGUGCCCGUGGGCAUGGGCCGCGUAGCGUUCCAAUUAUUUGCCGAUGCCAGCAGAAGUUGGAGGACGAAUUUCCAUUAUAUCACGCCCCCCACAUGGCUCGGUUUUGUGUUACGGUCGAGGAUGUGGUUAGAGGCUUCCCAAUGGGGGCUCGUCCGUUAUGGCACCUGGCUACGGCAACGUACGUUCAGUCUUACCCGUUCGGUGGAUCGUUUUGCAUAGUGCUUGCUAUAUCGCUCCACCCCACGGCACGAAAGUUAUGGUUACGUUUCCAGAGGUCGCUCAAACGUAGUUGGAUACCUUUGGGCCAAUGCCACCGGACCCCAACCUGUAAACGACUUCGCGUGAUAGAGCGUCACGACGACUUUCGGGUUUGGCAUCGUUCAAUACGCCGAACGCUAAUAGCCCUGCGAAAGCGAAGGGUUGCAAGGGAUGGAUCUGUUCCUUCCGACGGUCAGCCAACGUUACGUACUGCGUUGCGAAACACAGUUUCACACAAAUUUCUUACACGAGUACGAGAGACUAUCAACGAGGCCGAAUCGGAUGCCACUGUAUUUAACUUGCACAGAACUAGUCUAGUCGCCAUACUAAAUGAAGACUUGUCAGUCCGUCCCUAUUUCCUCACGUCUCAACGCUUUACGGCUAGUCAAUCCGUAAGUUUUCCCAUGUCAUGGGCACAGUGCGCCCAUUCGUUGGUCGCCCGCCAUAAGACUAAUCGUGCUCUUUGGGCGCCGCGCUUGUACGUAACGUUCCCACCAUUGAGACAACUAAGGCGUGCAUCCCCAGACCCGACUUGCACUACGGAAGGGUUGGGCCCGCCGCUACAGAUGCCCCUCGUAGGCUCGUGUCAUCCCGGACAAGCGCUCCUCAUGGCUUCACGCCAAACAUGGACCCUCCUUAAACGAGGCGAUUAUUCGACAGGCCAUUGUGGUCGAAGUGUCUGGAGACCACCGCUGUCUUGCUCGGCCUCCAAAGCCCCAUUCCCAGAUUUACGCACCCCUGACGCUUCGUUCAGGUUCGGCGCCAGCACAGGCCCCGCGUAUCUCCAUUCAUCACUCACAUUGGCUAGAUACACUCAAAUUAAGAGCGCAAAUACUAAACUGACCACGUACGUCUGUUCGUUGCCGUGCAUGAGGAUCCAUUUCAUUGUUCGGGGGACGAUAGCUAGAAUUCGCCAAAAACUCGCCCGUUGCUGUCCCUACUUAUCUGUAGGCCAACUCGGGCACCGAAUGGGCACACCCCAGUCCACACACGCUAAAACAAACUUAUGGCGCGUAAUGGCUAUGAGAUGCGCUGGAGGUAUCAUACCUACUCCGGCAACCGUCCCCCGUAUGGAUCGAAGUUACGGUCUGCUAGACACAGAGGAACCUCUAACCGGUGGAGUGAAGAUAUCUUCGAUCAUUCGAGAACUCUGCGAAGUGGACCCGAAUAAGAUUUUGGUUUGCUCCCGUCGGAGGCCGGGCACCCUUGACUGCGCCGAUGCUGGGGACGGGAAUGCAGUUGACGAAACAGAUACUGUUCACUCCGCAUAUUCAUGUCAUAGUCAUGGCUCUGAUGAUACUUUUUUAGCGAUCAGGGACCGGGACGGUCCACGUGAAUCAAAAGUAAUGGAGGCGAAUUUCACAUGUUCAGAUCGAUGGCAAGAUAAUAGGUUGGAGAGGGGGGUCCGGCCAGCUGUCUACCGUGAAUUGGACCUCAUGGAAGUCUUAGGAGACUCCGAGGAUUUGAGACCUCCCUGGUUGUCCUACUACUACUCGGUGCGGGGGGGCGGUCGCUCUAAGGAUAGGCCAGGCCAGCAGAAUCGCUAUGAAAUGCGACUUAGGUCGUUGUGGUACCUCAUCGACGUCUCUCCUAUUUAUACUCCCUCACUGGUAAUGGGCCAUAUUGUACACCCCGCUGGCCGUUCGUCCUCACGGACCGCGUAUCCUGAGCCUUCAUUUGGCCCGUUAGUCCGCGAUUGUUGCCUUUCUUCAAGGUUGCGGGCCUUCGAUGGGGCGGUCUCCAGUACUGUGCCCCUAAAUUAUCUCGUGUCGCUCCUCUACUCGGUAUUGACGCGAGAGCUAUUCAAUCGGCGGGUGAACCGGAGCAUCACACCUAGCUGGCGCGCAAUUGAUCAGACGACGGUGGCAAGCUUAGUCGUCCACAAGCUCUCGUUCGACUCCUUAUCGAAAUCGAAGUCACUCCCGUUGAAUUUGAUCUGCCAGACGCACCCAUUAGUUUUGUUCCUUGACUGUGAGCAUCUAAGCGAUAAGAUCUACGCACCACCAGGACCGAAUUUCCAAAUAAGCAAUUCCGCCUUAUCCGCAAGCUCGCCACUCAUAUCCACCCGCUAUUGUUGUCUUCAUCGUUGUUGCCCGACAUGUGACAGACUGCGCCGACUGGUCCAUUCUGGGACCCUCCCCAAGUGUGAAGUUGACGAAAGCCUGUAUUUAAACCGUACCCUCCACCAUACCAUUUCAUGGCAGGGUAUAAGAAUGUUAUUUAUACCCCCCGAGUUAGAUCACCGUCCCCCCGGUAUUGCCCAGGCAGCAGCCGGUGGGGAUCCUCUUUGCCAUCUUUAUGAUAUGACGAGCAAGACUUUGAUUCCGGAGCAUCAGCGACGGCCCCUGAUACCUCGAGCAUCACCAGGAUUAGCAACUGGCAGGGCACACGUGCGCGGCCCUAAAGCUGUCAAGGCAGCCCCUUGGUCCAUAAAUCGCAAAGUACUCGAGGGUGUGCAUAUAGACUCGCCAAUUCACUUUCCCCACGCCCUGUUUGUGCGGCGUUACUCGCUGGUCAAUCUCGUGUACAUUACGUGCGGUAUAGACGAACCUAUGGCCCGAGAAUGGCAGGGGGUCCGCAAGCCCAUCUGCACGAACCUAACCGCUACAAGAAAUCAUGCUCAUUGCCUAAAGACUGCGUUCCAGCUCUAUAACUGGAUAGACAAGUUUGCAGAAUCGAGUCCGCCAACCACACGGGUCCAAAAUGAGGAUGUGGAUGACACACUGGUUUCAGAGGAAGUUUCCCUGUGGCCUUAUCUGACUGGUAGGUGCGGCCCGACGUAUUUUUAUAUACACAUGCCCAUGAACAUUAGCUGUCGUUACAAAUCCGAUCCCUCCCCGUUUGAGCACAAAAAGAUAGACGGGUUUUGCGGACCCCAUCAGUCUGAAUACUGGACCACCACCCAAGGCUCUUUCUCCUGCACUUGGAUCGACCCAUCAGACCAACUCGCCCCGACAACCUUACCACAUAAGGCCAUCUUCUGGACUGGCAACUUGCGGCUGAACCCCUGUCUACGGGGCUUACCUUUGCGCGCGGAGACUUCUCAUCCGGUCGACCGGUUACCUCCCCCGCACUUCUUCCCGCUGGAGGUUCCGUCCCGACGGAUUACAAAACUAGGUUCCCGAGAUGAAGGUGAAUCAGCGCCGAAAAUCUCUUUACAUACAUCAACAUGUAAACUCACCCUUGGUAGAAUUUGCUUUAUUAUGGUGCGGGAUAUCCCAGGAACACUAUCGAGUAGACCGUUAAACAAAUUUUCUGUGGCGAACAUGGUCCUGUCUUCAGUACGUCGGGUACCAAUCGUGAGCGCGAGAGCAUUGCGUUGCCCUAUCUUUAGGCACCCAUGUGGUAUUCGUGCGGUUCUGCAGCAUUUGUCGACGAAUGGCGGACCCCAUGGUGUAGGUCAAGGUGACGAUCUGAAAUGGAUUUCCGGUACCGCGCGAUUGCGGCAUUCACCAGCUACAUUCGCGCCGGGAAGAGGUAGUGAGAAAUCUGCGGAGCUGUUUUGGGGGUUCAAUCCUCGGGCUAAGCAAACCGUAAGAUUUUCUAGAAAGGUCACCUGCAUAAUGGAGACUUGGUGCAGGAAAGACGCCUCAGUAAACCGGGCAUACCGACGCAUACUCCCGGACCAAGCGGUUAAGCCGUACAUAAGCAUUAUCCGACCGCGAUUGGUACGGGGCAAGUCCACUUUGGGGAGGAGAACGGCCUGCAGCACACAUGGCUACAAAGAGGCUCGGGGGGAUACGCAGUAUGGCUGGUGUUGCAUGUCCGACUUUUUAACGCCAAAGUGUAUCCUAGGCCCGAUAGACGGCGAAGUCAGAUGCAGUGGGUUCUUCAAGGUUACCCGACAACUACUCUUUUCCCUAGGCUGCUACCGAGGUUGUCACGGGGCAUCCUUCAGUACUAGCUCGUUCGAUCUUCCGUGGAAAGUCGCAUUCCGGGCCUUCGAUUGUACUGAGCUGAGUCCAGAAGUACCGGAUAGUGCUAGUAAGAAUUUUAUCAUAUACCAGACUGCUACAGCUAGCCACAUAGUGAAUUCACAUUUUACGUGGAAGGUCACAUCUAUCUUAGAUGUACUCAGGCGUCAGGGACAUUCAUAUGUCCGUGCAGCAAGAGGUCUCAGCUUAUAUUUGCCACACUGUGGCGCCAUGAUUCUAUCGAGUGAGGUAACAGUUUGCAAGCUGACUCCACUCGUUCGCGGACAAAUGGCACUGAGGUGUUGCGAAGCUUUUGGGGACAUGAACUUGCACUUGGGGUCGGCACGAUCGAGUAAUCGGGCUUGUGCUAUCACCCCCAGCACGUCCCGGUCACCCACAUUGAACGUAACGAUCGUUACUGUAACCGGGAAAGGUGCCCACUCACUCAGGCAUGUACUCCGCUGGGAGACAUACGUGUACCGCACCGUCGAGUCUUACAUAGGGCACCCUGUACCCAUGCGCACGUCUCCUCAGCGGCGACCUCUCACCUCCGUAUUUUUUCUUCCUAACUCGAUGUCGUGUACAAACCCUAUAGCGGUUGUAGAGGCCCUAAAAUACACCAAUUCCUUUUCUCGCGGCGGACGUCGCUUCGUCGUUCCCUUUUACGCAUUUGCGAUCCCACGGCCCCUGCUUCGUCCACGGAGAGGUCCUAACCCAGUCCGGCUAGACCGAAACUCGCCCUUGAUCUCGAGCAGAUUCGGCGCGAGCGGCUACGACGAGCUGGAAUCUAGAAACUUACUGGUCUGGACAGCUCUUGUUAUCCGAGAGCGCUGUGGCCGCCUAAUGCACAACGCACGCCUAAGAGGUUUAAGUACUAAGGAAGUACGACAGCAGGACGAAGCCAUAUUCCAUCUAUGGGGCAUUUUCUUAAGUUCAUGGGCGCAUUCAGCUAUGGCUGUAAUAAAACACGCCCUUUUGUCUACCGGUUUCCGCAUUGGGGAUGGAGCGUCCAGUGAACCACACCUAUGCCCGAUUUUUAGGCACAUGCAGGAUCGUCGUGUUCAGUCGAACGGAUUUGGCCGACACCUACAUCUGUUCCUGCUGCCGAGCGGUCGGUCGUUGCUCACCCUCAGAGUCCCAAAAAAGAGCCGAAAAGAAACCCCGUCCCAAUGCUGUCGGCUUAGGCUAACCAAGAGUCCCAAGGAGAGCAGGUACAUACUGGUUCUCUUAGCGUUGUGUAUAACGUACUAUGUUCUACAUGCGACGAUCUAUGCUUUUUGUGGCGAGCAUCCAAUAGCACGGGUGAUUCGGAUACGUACAUACGGGGAGGGCGCGAUGCCAGAUCACUUAGCUCCCCCCAAAGGCAACCCCCAACCGUAUAUUGAGGACGUUCACAGCCGGUCUUCAAAUGAAUGGUUCGACCGGGCUAGAGGGCGUAGUAAGCGUAAUCGCGCAGCCAUCCAUGGGCGCCGUAAGUGGCGAAGUAACUAUCUGGCAGUCGCAAGCGCCUUCAGACACGGCAGCCACGAUCGUAUUCACGACGUUCUUCACAAAGACCUGCAACGGUUGACUUACCAGGAUGGAGGGCACACGCAGUACCUAGUUCAACGGCGAAACCAGCAAGGGUUCACAACCAUACUGCCAAAUAGGAUGCAUUCCUCGGAAAAUGUACAGGUCGCCCGCAAUCACCGACCACGUGGGACUGCCCUUGCCAUCAGCGCCAGAAAGCUGGGACAUCGCCUAACCGGUUCCUCGUCCUUGUUCGCUUGUGUGCGUAUGAGCCGCACCCCGAUAAACCAGUGUUGGCACGUCAUACUGGGGCCUCAUGGGGGCGGUUCGCGGUUCGCGUCGCGGUGUUCUAACCCAGAAAAUCCUGCAAUCUCGGCGAGAGGAACAACACGAUGGGACUUUACUAAGAUAACAGUCAUCAAGACGAUUGUGUAUGAUUUAGGGACGCUUGGGCGGCGCGGGCGACGUACAGCAGUCCGUUCAAAUCCGUUGAGGAUUAACGGCGGUUCCCAUUCACGCGUGACAGAUGCACGGAAAAAUAACCCAAGGCAUACCAGCAUUGUACAUUGGAAUGUCUAUACAACAGACUGGAGGUUUUCUUCCUGGGUCAUGACAGCCCGGCGGUUGAAAAGACUACGAGGUACUUAUCUAAACUAUCGAGUUCUCCCCGUCCAGGAGCUCAUCCAGGUACUUGUAGGCUUGCUUAGGUUCUUCUGGCGGUCUCGAUGCAACCCGCGUGGCCAUCUGUGUAGGUUGCAUACCUCCUGCUCAUCCAGGUUACCGAGGAUCUGCUGGUCCGGGACGGAAGCAUGUCCAAGCAAACGCUCUAAGGGAGCUAUUGGCAAUUUCUUUGCUCCUGUCCAUGUUUGUAGAUUCCCUUUACACGCACGACCAAUCUUGGCCCUUAUCGAUGUCAACAUCAUAGAAGCGAAAGGUCUGACAAGACUUGGUGCUGACGAUGGAAAAACAGUGAUCCACUGGCUGCUAUGCCCGACUCUUCUCACUAAACUUCGCAACGAUUGCAUUCUCGAGAUAUGCAUGUCCUUAAUUCACUUCUGCGCACUCUGUGUGAGAGGCCGUUUCCAACCCCUGAAGAGGCUCACCGCCAACGGCACUAGUGACAUCGGUUGCCCAAUGGCAUCGACGGCUCGGCUCUUUGCACACAAUCAGAGCGCUGUUCAUUCCCUCCACACACAUGUGCUCCUAAUUCGUCGGCUCAAGGCCGUGGACUGCCUAAGUUCUGGAUCCGACAUCCCGGUGGUGGGUAGUAUGACGCCGAACAUAACCGCCUUGUGGCUAUCUCGAGGAAAUCGGGGGAAACGAAAUAACGCAAGGAGAUUCCCCGCAAGAACUAACUUGGGUUCAUGGACAUCAGGGCGGGGCUUCCACCAGCCACAGGCGCUUAACGUACCUUGUAAAUCCGUCGAGCGUGCGUGCCCCGGUAUUGUACCGAUUUCCCCACCCGACUAA"
out = ""
max = len(txt)//3
# for i in range (len(txt)//3):
for i in range (max):
    frag = txt[i*3:i*3+3]
    prot = protein_dictio.get(frag)
    if prot == "Stop":
        break
    else:
        out = out + prot
    
print(out)
# print(txt[1:2])

    
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        